### ISSUE TITLE
Migrate presets separateMajorReleases and separatePatchReleases

### ISSUE THREAD

**Issue by BrianChristie** [renovatebot/presets#105]
The following config options were renamed in https://github.com/renovatebot/renovate/issues/1952 
* multipleMajorPrs => separateMultipleMajor (false)
* separateMajorReleases => separateMajorMinor (true)
* separatePatchReleases => separateMinorPatch (false)

It looks like the default preset has not been updated and still sets the old config option names:
* `separateMajorReleases`
* `separatePatchReleases`
https://github.com/renovatebot/presets/blob/5108b129a99d61a050507e98730c001591a1948a/packages/renovate-config-default/package.json#L93:L100

The Documentation has been updated to reference only the new config options:
https://renovatebot.com/docs/configuration-options/#separatemajorminor

I am not entirely sure that I understand how this is working, but it seems that the presets need to be migrated to the new config name. If yes, how do you prefer to migrate this change?

I see the following options:
#### A 
* Rename the preset to match the new config names `separateMajorMinor`, `separateMinorPatch`, and change the config option to match
* Change renovate-config-base to reference the new preset names
* This will break anyone who’s directly referencing the old preset names
#### B
* Add a new preset with the new config names  `separateMajorMinor`, `separateMinorPatch` and matching config options
* Leave the old preset names `separateMajorReleases` and `separatePatchReleases` in place, and change the config options set to `separateMajorMinor` and `separateMinorPatch`, to not break people referencing them directly

Thanks!

**Comment by rarkins** [comment]
@BrianChristie thanks for the detailed summary - I hadn't noticed this problem. What I decided to do was leave the old preset names and just change the config inside them. As you noted, we need to leave the old ones in place anyway for backwards-compatibility, so I decided to choose for "Keep old preset names which you could argue are outdated but actually still describe their purpose pretty well" rather than "Maintain two presets that do the same thing but have different names forever".
