### ISSUE TITLE
Next.js monorepo should group next and next-server

### ISSUE THREAD

**Issue by damusnet** [renovatebot/presets#114]
Hello,

I saw an update to the [Next.js monorepo definition](https://github.com/renovatebot/presets/commit/b724bb28ffba999578529933f221560e4dd05395) recently, but somehow `next` and `next-server` upgrades still occur separately:

![image](https://user-images.githubusercontent.com/433409/56516255-f3bdf600-6507-11e9-8c1d-384b25d298eb.png)

Can we group them please?

**Comment by rarkins** [comment]
The `next-server` package has incomplete metadata and gives no indication of its source repository ([ref](http://registry.npmjs.org/next-server)). I've submitted this pull request to correct it: https://github.com/zeit/next.js/pull/7105

If the PR is not accepted in a timely manner then we could add a manual workaround to define the group by package names rather than source.

**Comment by damusnet** [comment]
@rarkins sounds good! Thanks for taking care of it! Looks like it was merged immediately!
