### ISSUE TITLE
Add group for .NET Core / ASP.Net Core Docker containers

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/presets#155]
Microsoft is using a variety of Docker images on which .NET Core & ASP.NET Core applications depend, such as `mcr.microsoft.com/dotnet/core/sdk` & `mcr.microsoft.com/dotnet/core/aspnet`.

For Promitor I depend on those and receive update PRs, but they are seperated (example: https://github.com/tomkerkhove/promitor/pull/831 & https://github.com/tomkerkhove/promitor/pull/832) which is not ideal so I'd like to group them so that the CI works.

I'm looking to open a PR for adding this and was wondering if monorepo Docker images should also end up in https://github.com/renovatebot/presets/blob/master/packages/renovate-config-monorepo or if there are better ways to do this?

**Comment by rarkins** [comment]
@tomkerkhove it might be best to add them as an entry into https://github.com/renovatebot/presets/blob/master/packages/renovate-config-group/static-groups.js

In a way there are at least three tiers of package groupings I've seen:
- True monorepo. From the same repository and should always be updated together
- Related packages from different repositories but should always be updated together because they often depend on each other
- Related packages that should *often* be upgraded together or things break, but not always

I'm still trying to work out how "opinionated" Renovate should be in this regard. The `group:recommended` preset is included as part of `config:base` and so far I think it's OK to put the last two tiers into it.

**Comment by tomkerkhove** [comment]
Thanks, I'll send a PR to add a new group!

**Comment by tomkerkhove** [comment]
I've opened a PR, feel free to let me know if this would work but I'm not sure 😅
