### ISSUE TITLE
Invalid configuration option: combinePatchMinorReleases

### ISSUE THREAD

**Issue by timReynolds** [renovatebot/presets#23]
I've tried setting up one of our larger services today to use renovate. Using the `config:base` option we'd end up with ~35 initial PRs so I was looking to tweak the settings to create larger PRs that group minors and patch versions.  

Looking over the configuration I decided on the following;
```
{
  "extends": ["config:base"],
  "combinePatchMinorReleases": true,
  "separatePatchReleases": false,
  "encrypted": {
    "npmrc":
      ""
  }
}

```

Renovate now gives me the following error;
```
Action Required: Fix Renovate Configuration

There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

File: renovate.json
Error type: The renovate configuration file contains some invalid settings
Message: Invalid configuration option: combinePatchMinorReleases

Once you have resolved this problem (in this onboarding branch), Renovate will return to providing you with a preview of your repository's configuration.
```

Based on the documentation I could see these options have the potential to conflict. 

- combinePatchMinorReleases: "Combine any patch and minor upgrades together into same branch/PR"
-separatePatchReleases : "Separate patch and minor releases of dependencies into separate PRs"

Whats the best way to resolve this? Ideally, I think I'd like all the patch/minor updates in one PR and then majors one per dependency. This is probably less ideal long term but initially we're going to have a lot of PRs to process otherwise.

**Comment by rarkins** [comment]
The reason for the config error is that `combinePatchMinorReleases` is actually a config preset, rather than a native config option. So you would add it like this to remove the error:

```
{
  "extends": ["config:base", ":combinePatchMinorReleases"],
  "separatePatchReleases": false,
  "encrypted": {
    "npmrc":
      ""
  }
}
```

However configuring it is redundant because:
(a) `:combinePatchMinorReleases` is included with `config:base`
(b) It's the same thing as `"separatePatchReleases": false`

So really the above config is the same as:

```
{
  "extends": ["config:base"],
  "encrypted": {
    "npmrc":
      ""
  }
}
```

What this setting does is control whether to combine or separate patch/minor of the **same** dependency. e.g. if you have dependency `foo@1.0.0` currently and both `foo@1.0.1` and `foo@1.1.0` exist, then do you just want one PR for `foo@1.1.0` or do you want separate PRs for each? Default behaviour is just one PR, which is surely what you want.

Combining updates together always comes with tradeoffs. If you combine a lot together and one of them is broken, then you're stuck not upgrading any without manual intervention. If maybe *two* of them are breaking in the same PR then it can be a real nightmare to try to work out what went wrong as it's not always obvious once you get seemingly unrelated failures everywhere.

At the most I'd recommend combining all patch/minor from different dependencies into one PR and then keeping each major PR separate. To do that you can try:

```
{
  "extends": ["config:base"],
  "minor": {
     "groupName": minor
  },
  "encrypted": {
    "npmrc":
      ""
  }
}
```

**Comment by timReynolds** [comment]
This fixed the issue.
