### ISSUE TITLE
Receiving Report for Invalid Configuration

### ISSUE THREAD

**Issue by hutson** [renovatebot/presets#25]
We're receiving a report for `Action Required: Fix Renovate Configuration` in the following issue - https://github.com/conventional-changelog/conventional-changelog/issues/302

I threw the JSON file into a JSON validator and it passes.

It's also the exact same file as we use for [`releaser-rools`](https://github.com/conventional-changelog/releaser-tools/blob/master/renovate.json).

**Comment by rarkins** [comment]
Seems like the bot just closed it itself. I’ll look at logs later to see what error caused it and if we can prevent the config warning in such cases

**Comment by rarkins** [comment]
Strangely, GitHub returned a 404 for the `renovate.json` even though it was included in the file list for the repo (and I assume existed). We catch that at the platform level and return null, which then manifested as "invalid JSON". I changed the logic to throw an error in such cases instead, to abort the renovation. The second time it ran was fine, so the issue was closed.
