### ISSUE TITLE
Preset name not found within published preset config

### ISSUE THREAD

**Issue by ryasmi** [renovatebot/presets#50]
Hey, the bot created an [issue with our Renovate config](https://github.com/LearningLocker/xapi-validation/issues/49), but this had been working and I'm not sure what the issue is with the config unless something has changed here recently that means it's no longer valid.

This is [our Renovate config](https://github.com/LearningLocker/xapi-validation/blob/master/renovate.json):
```json
{
  "extends": [":library"],
  "automerge": true,
  "automergeType": "branch-push",
  "major": {
    "automerge": false
  }
}
```

**Comment by rarkins** [comment]
@ryansmith94 sorry for the inconvenience. npmjs had a major problem yesterday where they "lost" something like 5-10 hours of published versions. The big problem is that some versions that were published successfully later disappeared - it would be less bad if it was only a matter of published versions never appearing in the registry, because then nobody would have upgraded to them. What I didn't realise was that (a) they didn't properly fix the problem by restoring all missing versions, and (b) one of Renovate's preset configs was included in the missing versions. So today I updated a different preset that relied on an already-published-but-then-lost version and BOOM. I manually ran Renovate over that particular repo just now to get it closed, and any other should get picked up in the next hour.

**Comment by ryasmi** [comment]
Hey @rarkins, no worries, thanks for the quick response 😄Ah haha nice. Cool, good to know all is well now. Sucks that you briefly got screwed by NPM, not the first time that's happened to someone haha.

**Comment by rarkins** [comment]
@ryansmith94 unfortunately they are not acknowledging that they allowed versions to be published and then disappear. They treated it as a "publishing failed" problem and therefore considered the fix to be "publishing now doesn't fail anymore" and ignore that there's still a bunch of missing published versions. I think I republished all the ones I depend on now.

**Comment by ryasmi** [comment]
@rarkins ah man, that sucks. You must have had a rough day tracking down the packages that failed to publish, bit annoying when you probably a bunch of other stuff to do. Nice, I'm sure someone will comment on this issue or create a new issue if something didn't get republished :smile:
