### ISSUE TITLE
Add a lintersNonMajor group?

### ISSUE THREAD

**Issue by voxpelli** [renovatebot/presets#61]
Major linter upgrades almost always break builds, but non-major ones should almost never do it.

Having a linters group limited to non-majors, like the `testNonMajor`, would be neat 👍 

(Btw: Apart from my personal testing of your GitHub app, we're also trialing it internally at @Sydsvenskan now – works nicely so far 🎉)

**Comment by rarkins** [comment]
@voxpelli since your suggestion here, I added the [updateTypes](https://renovatebot.com/docs/configuration-options/#updatetypes) field to `packageRules`, which should make it easier to write a rule like this. I think this concept of "non-major" might only apply when you have mixed groups though. e.g. if it's a monorepo then you want them grouped still even if they're major.
