### ISSUE TITLE
Semantic commit mode auto-detection problem

### ISSUE THREAD

**Issue by edmorley** [renovatebot/presets#8]
In our initial PR (mozilla/treeherder#3025), the example commit messages contain the `fix(deps)` prefixes, even though we don't use semantic commits. This was initially confusing, since looking at the config docs, the default for `semanticCommits` is `null` ([from here](https://renovateapp.com/docs/configuration-reference/configuration-options#semanticcommits)) which is auto-detect, which presumably should have turned off the prefixes for us.

I'm guessing that since the PR is using `config:base`, the included `:semanticPrefixFixDepsChoreOthers` preset is overriding the auto-detect behaviour to always enable semantic commit messages?

Presuming that's the case:
1) Should `config:base` instead maintain the auto-detect behaviour?
2) Is there a simple way to override the current `config:base` usage of `:semanticPrefixFixDepsChoreOthers`? Looking at the source ([here](https://github.com/singapore/renovate-config/blob/dbe6d310deeb47be1438a28394fcbc386ffa7171/packages/renovate-config-default/package.json#L89-L124)) it seems I'd have to override x4 (one for each of dep/devDeps/...)

Many thanks :-)

**Comment by rarkins** [comment]
Hi @edmorley,

You are right that semantic prefixes should be autodetected as false if they are not already in use in the repo.

I took a look at the mozilla/treeherder logs right now and see:
```
{"name":"renovate","level":20,"repository":"mozilla/treeherder","packageFile":"package.json","msg":"getCommitMessages","time":"2017-12-18T05:33:56.046Z"}
{"name":"renovate","level":20,"repository":"mozilla/treeherder","packageFile":"package.json","msg":"GET repos/mozilla/treeherder/commits","time":"2017-12-18T05:33:56.058Z"}
{"name":"renovate","level":20,"repository":"mozilla/treeherder","packageFile":"package.json","msg":"Found semantic commit type eslint - enabling semantic commits","time":"2017-12-18T05:33:56.245Z"}
```

It seems like the third party semantic commits detector I use is a little too eager to classify as "eslint" - I saw this in one other repo recently too, so might dig into it more after this.

Anyway, you can manually override this with the following config:
```
{
  "extends": [
    "config:base"
  ],
  "semanticCommits": false
}
```

You do not need to override the settings from `:semanticPrefixFixDepsChoreOthers` because that only controls what the semantic prefix *looks* like, and not whether it's on or off.

I tested it here and assume it's like you want: https://github.com/renovate-tests/treeherder/pull/1

**Comment by edmorley** [comment]
Ah makes sense thank you. I've updated the PR summary to reflect that this was a auto-detection issue rather than a Renovate defaults vs `config:base` issue.

On a related note, I wonder if `config:js-app` should default to disabling semantic commit mode? (Presumably apps are less likely to not use it? Though I guess this wouldn't be necessary in a future where auto mode was more reliable?)

**Comment by rarkins** [comment]
I don't think we can make the assumption that apps don't use semantic commits, so I think I'll leave it as-is. I'm going to try to reduce the false-positives though.

**Comment by rarkins** [comment]
BTW I think I have spotted the problem. The commit analyzer is returning "eslint" as the semantic commit type. I need to confirm, but I'll probably add a rule so that "eslint" style semantic commits are considered *disable* as if there were none at all.
