### ISSUE TITLE
group:allNonMajor dont group patch releases into one PR

### ISSUE THREAD

**Issue by aldarund** [renovatebot/presets#85]
Here is custom preset used
https://github.com/nuxt/renovate-config-nuxt

Here is grouped PR https://github.com/nuxt/nuxt.js/pull/3986
And here is patch releases each was opened with a separate PR 
https://github.com/nuxt/nuxt.js/pull/3979
https://github.com/nuxt/nuxt.js/pull/3981
https://github.com/nuxt/nuxt.js/pull/3977
etc
According to docs

> Group all minor and patch updates together

They all should be in one PR, not a separate PR for each patch release

**Comment by rarkins** [comment]
@aldarund 	thanks for the report, I will take a look

**Comment by rarkins** [comment]
@aldarund after the fix, you can see all the patch updates have been combined into this PR: https://github.com/nuxt/nuxt.js/pull/3991

**Comment by aldarund** [comment]
@rarkins ye, thanks. But now there other problem Release notes only embed for the first dependency as you can see in that PR

**Comment by rarkins** [comment]
Many packages don’t actually write release notes for patch releases so it’s possible there’s just none others to display. I’ll check later though, in case.

**Comment by aldarund** [comment]
@rarkins not the case, i checked it first.
See for example this previous PR for postcss-preset-env ^6.0.3 -> ^6.0.7
https://github.com/nuxt/nuxt.js/pull/3982
There is release notes. But in that new combined PR its still this update for postcss-preset-env but no release notes anymore.

**Comment by rarkins** [comment]
Thanks for checking it. I think I know what the problem is and it's a strange one. The babel release notes are huge and meanwhile there's a limit to how many characters you can fit in a GitHub PR body, so a lot had to be truncated. Notice there's no "Created by Renovate Bot" footer there either. Anyway right now we do the simplest approach and simply truncate PR body text starting from the beginning, but in this case it's meant only babel can fit. Maybe we can work out an "algorithm" to reduce the number of notes proportionally, although it's harder than it sounds.

**Comment by pi0** [comment]
@rarkins WoW thank for this quick fix. Regarding reducing first post body size, we may break long release notes into more replies. I will put my proposal into renovatebot/renovate#2569.
